import json
import random
import time

from datetime import datetime


class Dependency:
    tempatLahirArray = [
        "Ambon",
        "Balikpapan",
        "Banda Aceh",
        "Bandar Lampung",
        "Bandung",
        "Banjar",
        "Banjarbaru",
        "Banjarmasin",
        "Batam",
        "Batu",
        "Baubau",
        "Bekasi",
        "Bengkulu",
        "Bima",
        "Binjai",
        "Bitung",
        "Blitar",
        "Bogor",
        "Bontang",
        "Bukittinggi",
        "Cilegon",
        "Cimahi",
        "Cirebon",
        "Denpasar",
        "Depok",
        "Dumai",
        "Gorontalo",
        "Gunungsitoli",
        "Jambi",
        "Jayapura",
        "Kediri",
        "Kendari",
        "Kota Administrasi Jakarta Barat",
        "Kota Administrasi Jakarta Pusat",
        "Kota Administrasi Jakarta Selatan",
        "Kota Administrasi Jakarta Timur",
        "Kota Administrasi Jakarta Utara",
        "Kotamobagu",
        "Kupang",
        "Langsa",
        "Lhokseumawe",
        "Lubuklinggau",
        "Madiun",
        "Magelang",
        "Makassar",
        "Malang",
        "Manado",
        "Mataram",
        "Medan",
        "Metro",
        "Mojokerto",
        "Padang",
        "Padang Panjang",
        "Padangsidimpuan",
        "Pagar Alam",
        "Palangka Raya",
        "Palembang",
        "Palopo",
        "Palu",
        "Pangkalpinang",
        "Parepare",
        "Pariaman",
        "Pasuruan",
        "Payakumbuh",
        "Pekalongan",
        "Pekanbaru",
        "Pematangsiantar",
        "Pontianak",
        "Prabumulih",
        "Probolinggo",
        "Sabang",
        "Salatiga",
        "Samarinda",
        "Sawahlunto",
        "Semarang",
        "Serang",
        "Sibolga",
        "Singkawang",
        "Solok",
        "Sorong",
        "Subulussalam",
        "Sukabumi",
        "Sungai Penuh",
        "Surabaya",
        "Surakarta",
        "Tangerang",
        "Tangerang Selatan",
        "Tanjungbalai",
        "Tanjungpinang",
        "Tarakan",
        "Tasikmalaya",
        "Tebing Tinggi",
        "Tegal",
        "Ternate",
        "Tidore Kepulauan",
        "Tomohon",
        "Tual",
        "Yogyakarta",
    ]

    jenisKelaminArray = ["Laki-Laki", "Perempuan"]

    tahunMasukArray = [2020, 2021, 2022]

    tingkatArray = ["X", "XI", "XII"]

    jurusanArray = ["AKL", "BDP", "MM", "OTKP", "PKM", "RPL", "TKJ"]

    rombelArray = [
        "AKL",
        "BDP",
        "MM",
        "OTKP 1",
        "OTKP 2",
        "OTKP 3",
        "OTKP 4",
        "PKM",
        "RPL",
        "TKJ",
    ]

    nameArray = [
        "A. Prabhu",
        "A. Budi Pranoto",
        "AAJ Batavia",
        "Aam Dewi Hamidah",
        "Aarti Lohia",
        "Abdul Hadi Ismail",
        "Abdul Rachman",
        "Abdul Rahman",
        "Abdul Rifai Natanegara",
        "Abdul Slam Tahir",
        "Abdullah Alatas",
        "Abu Djaja Bunjamin",
        "Abu Hermanto Budiono",
        "Achirsyah Moeis",
        "Achmad Fadjar",
        "Achmad Faried Joesoef",
        "Achmad Kalla",
        "Achmad Latief Alwy",
        "Achmad Nugraha Djuanda",
        "Achmad Sandi",
        "Adam Sautin",
        "Ade R. Syarief",
        "Ade Tjakralaksana",
        "Adelina Prasetio",
        "Adhi Utomo",
        "Adhi Utomo Jusman",
        "Adi Bisono",
        "Adi Sasono",
        "Adi Sumito",
        "Adimitra Baratama Nusantara",
        "Aditya Koeswojo",
        "Adji Muljo Teguh",
        "Adnan Kelana Haryanto",
        "Adri Achmad Drajat",
        "Adriana Maya Politon",
        "Adryansyah",
        "Afandi Hermawan Oey",
        "Tjoeng Anna Chrisnadi",
        "Agam Nugraha Subagdja",
        "Ago Harlim",
        "Agoeng Noegroho",
        "Agung Podomoro Group",
        "Agung Salim",
        "Agung Tobing",
        "Agus Djohari",
        "Agus Hartono Lie",
        "Agus Lasmono Sudwikatmono",
        "Agus Leman Gunawan",
        "Agus Makmur",
        "Agus Nursalim",
        "Agus Pranoto Setiadi",
        "Agus Purnomo Edhi",
        "Agus Soenong",
        "Agus Suherman Wirjan",
        "Agus Susanto",
        "Agus Tjandra",
        "Agus Widagdo",
        "Agustinus Prasetio",
        "Agustinus Wishnu Handoyono",
        "Aguston Makmur",
        "Ahadiat Wargana",
        "Ahmad Dipoditiro",
        "Ahmad Marda",
        "Ahmad Rahman Pasaman",
        "Ahmaddin Ahmad",
        "Ahmades Miqailla",
        "Ahsanil Gusnawati",
        "Aida Ishak",
        "Aiwy",
        "Aizid Syafriel Adjam",
        "Aji Bayu Wirrotama",
        "Akbar Yoso Trisedia",
        "Alan Clark",
        "Alan Robertson Clark",
        "Albert Cahyadi Sukandadinata",
        "Albert Kongoasa",
        "Albert Sugianto",
        "Albert Suherman",
        "Aldo Putra Brasali",
        "Alex Ivan Tanoyo",
        "Alexander Hermas Wolfe",
        "Alexander Johan Widjaja",
        "Alexander Thaslim",
        "Alexandra Miksar",
        "Alfari Narindra",
        "Ali Alimsyah",
        "Ali Chendra",
        "Alice Haryono",
        "Alien Wibowo",
        "Aling Hermawan Oey",
        "Alisyahrazad Hanafiah",
        "Allan Dijaya Keller",
        "Allan Tjahja Tjao",
        "Aluinanto Sandjojo",
        "Alvin Gozali",
        "Alwi Alatas",
        "Alwijaya Aw",
        "Amalia",
        "Amalia Aristiningsih",
        "Amaluddin Djambak",
        "Aman",
        "Ameesh Anand",
        "Amelia Kurniawan",
        "Amelia Mulyono",
        "Amin Halim",
        "Amin Supriyadi Liu",
        "Aminoto Sutandi",
        "Aminoto Sutandy",
        "Amrullah Hasyim",
        "Amy Delia",
        "Anak Agung Alit Wiradarma",
        "Anak Agung Gde Agung",
        "Ananda Soewono",
        "Ance Anggraeny",
        "Andang Bachtiar",
        "Andhika Anindyaguna Hermanto",
        "Andi Achmad Dara",
        "Evi Yulisma Harahap",
        "Andi Gunawan Wibowo",
        "Andi Pravidia Saliman",
        "Andi Zainal A. Dulung",
        "Andiko Ardi Purnomo",
        "Andre Abdi",
        "Andre Johannes Mamuaya",
        "Andre S. Prijono",
        "Andre Sukendra Atmadja",
        "Andreas Andikha Bunanta",
        "Andreas Kastono",
        "Andreas Kongoasa",
        "Andreas Tjahjadi",
        "Andrew I. Sriro",
        "Andrew K. Labbiaka",
        "Andrew McKay",
        "Andrew Mellon Priasmoro",
        "Andrew Tanoto",
        "Andrew Thomas Eriksson",
        "Andrie Setiawan Yapsir",
        "Andry Irwan Djugo",
        "Andry Pribady",
        "Andry Setiawan",
        "Andy Nugroho Purwohardono",
        "Andy Soewatdy",
        "Andy Wiryanto Ong",
        "Ang Lian Ping",
        "Ang Rianti",
        "Ang Rosabella Martina",
        "Angela Lestari Widjaja",
        "Angelique Stampfer",
        "Angie Christina",
        "Angus Maclachlan",
        "Angus Nelson Karoll",
        "Ani Sim",
        "Anil Kumar Lachman Panjabi",
        "Anindya N. Bakrie",
        "Anita Kalim",
        "Anita Ratnasari",
        "Anna Solana Hamami Kadarachman",
        "Anna Sri Dewi Sianto",
        "Annie Halim",
        "Anthony Brent Elam",
        "Anthony Dominic Byron",
        "Anthony Kurniadi",
        "Anthony Salim",
        "Anthony Siswanto",
        "Anthony Wijaya",
        "Anton Henning Linderum",
        "Anton Kusuma",
        "Anton Santoso",
        "Anita Marta",
        "Anton Sugiono",
        "Anton Tjahjono",
        "Anton Wiratama",
        "Antonius Mulya Saputri",
        "Antony Gunawan",
        "Anuj Ralhan",
        "Anwar Lim",
        "Anwar Saebe",
        "Ardas Dipa",
        "Ardiani Kartika Sari Subianto",
        "Ardy Wiria",
        "Ari Hardono Suroso",
        "Ari Indra Gautama",
        "Ari Rophian Perdana Ariwibowo",
        "Ari Sulistio",
        "Arianto Prasetio",
        "Arianto Wisnu Triyatno",
        "Arie Kondang Kresnadi",
        "Arief Prijatna",
        "Arief Santoso",
        "Arief Wiyoso Aswismarmo",
        "Yvette Suryatenggara",
        "Arif Rachmat",
        "Arifin Yohan",
        "Arini Saraswaty Subianto",
        "Aris Agung Budiman",
        "Aris Yuwono Ang",
        "Aristotle",
        "Arjen Tridarma Darmawan",
        "Arlehne Purnomo",
        "Arman Sutedja",
        "Armedta Budi Asmara",
        "Armeilia Widayanti Subianto",
        "Arniaty Achmad",
        "Arta Satria Soebandi",
        "Artha Mitra Interdata",
        "Arwan Ahimsa",
        "Ary Surya",
        "Arya Widjaya",
        "Aryo Bimo Notowidigdo",
        "Ashwani Chowdhry",
        "Ateng Suhendra",
        "Ateng Sulestio",
        "Atira Aksa",
        "Aubrey Bobb",
        "Aurelia Supardi",
        "Aviariananto Sukotjo",
        "Awiek Lestari Rahayu",
        "Aziar Zain",
        "Azir Azwien Jenie",
        "B. Dorpi Parlindungan",
        "Bachrumsyah Hamzah",
        "Baduraman Dorpi Parlindungan",
        "Bagus Panuntun",
        "Baldeo Singh",
        "Bambang Hartono",
        "Bambang Irawan Massie",
        "Bambang Niaga Tjiputra",
        "Bambang Rahardja Burhan",
        "Bambang Subianto",
        "Bambang Sugianto",
        "Bambang Suhandi",
        "Bambang Sujagad Susanto",
        "BamBang Sumantri",
        "Bambang Tijoso Tedjokusumo",
        "Bambang",
        "Derice Alda",
        "Malcolm Alda",
        "Meyrick Alda",
        "Sumantri",
        "Banbang Panutomo",
        "Bank Bira",
        "Bank Centra",
        "Bank Danamon",
        "Barlianto Ronald",
        "Basuiki Puspoputro",
        "Batavia Prosperindo Sekuritas",
        "Bayu Irianto",
        "Bayu Prawitasari",
        "Bayu Virgan Triyatno",
        "Beata Ida Hartono",
        "Beatrice El",
        "Belinda Natalia Tanoko",
        "Ben Morice",
        "Beng Phiau",
        "Bengt Carl Gustav Thornberg",
        "Benjamin Subrata",
        "Benjamin Wong Siong Yuit",
        "Benny Setiawan",
        "Benny Tenges",
        "Benny Tjokrosapoetro",
        "Beny Haryanto",
        "Bernadette Ruth Irawati",
        "Bernie Prajoga",
        "Betty Ang",
        "Bimo Pramudyo Soekarno",
        "Bimo Surono",
        "Bing Gondosubroto",
        "Bintoro Wong",
        "Bismarka Kurniawan",
        "Bob Yanuar",
        "Bobby Andhika",
        "Bobby Iman Satrio",
        "Boedi Sampoerna",
        "Boediyanio Gondotirto",
        "Boelio Muliadi",
        "Bong Kiu Nio",
        "Bong Tjen Khun",
        "Tjong Njuk Fon",
        "Bonny Budi Setiawan",
        "Boy Gemino Kalauserang",
        "Brett Hay",
        "Budi Arsil",
        "Budi Basuki",
        "Budi Christranto",
        "Budi Enijati Maria Soedjana",
        "Budi Ferdinandus",
        "Budi Mulio Utomo",
        "Budi Santoso Taruno Sembodo",
        "Budi Setiadharma SH",
        "Budi Sintoro Then",
        "Budi Surjana",
        "Budi Widyadi",
        "Budi Yanto Lusli",
        "Budiarto Karim",
        "Budiawan Jusmin",
        "Budiman Effendi",
        "Budiono",
        "Budiono Darsono",
        "Budiono Tanbun Boen",
        "Budy Hartono Santosa",
        "Budyanto Totong",
        "Burhansjah",
        "Bustami",
        "Calvin Lukmantara",
        "Cameron Robert Knox",
        "Candra Winoto Salim",
        "Carlos Tarazona Ramirez",
        "Caroline",
        "Catherine Gina Hambali",
        "Catherine Hambali",
        "Catherine Yoshawirja",
        "Cecilia Tejowarno",
        "Celin Tanardi",
        "Chairul Iskandar Zulkarnaen",
        "Chan Hiong Poh",
        "Chander Vinod Laroya",
        "Chandra Widjaja",
        "Chang Mei Yu",
        "Charles Louis De Queljoe",
        "Charlie Kasim",
        "Charterhouse Limited",
        "Cheam Soon Tee",
        "Chenry Micron Mor",
        "Chew Say Loo",
        "Chin Chin Chandera",
        "Choo Khee",
        "Chris Fong",
        "Chris Newton",
        "Christanto Santoso",
        "Christian Dieter Scholz",
        "Christian Leuchtenberg",
        "Christian Nainggolan",
        "Christian Parlaungan Mulyanto",
        "Christian Sandy Rachmat",
        "Christian Sugiarto",
        "Christiana Halim",
        "Christiana Niowni",
        "Christianto",
        "Christine Russel Carter",
        "Christina Harapan",
        "Christina Sumarlin Pribadi",
        "Christopher Basil Newton",
        "Christopher Carson",
        "Christopher Fong",
        "Christopher James Garrard",
        "Christopher Tanuwidjaja",
        "Chu Jackson",
        "Chui Hing Keung",
        "Cindy Tanuwidjaja",
        "Cindy Anastasya Kurniawan Oey",
        "Citrawinda Priapantja",
        "Clarence Leonard Stratton",
        "Crescento Hermawan",
        "Dadi Sukarso Yuwono",
        "Damsiruddin Siregar",
        "Dan Brown",
        "Danan Kadarachman",
        "Dani Ismulyatie",
        "Daniel",
        "Veronica Yuwono Yu",
        "Daniel Indra Djajadi",
        "Daniel Kurniawan Lukman",
        "Daniel Marathon",
        "Daniel Podiman",
        "Daniel Wewengkang Korompis",
        "Danielle Catharina Willemijn Maria Van Poppel",
        "Danny Juwono",
        "Linda Liani Janti Senjaya",
        "Danny Nugroho",
        "Danny Tjiu",
        "Dany Subrata",
        "Darjoto Setyawan",
        "Tjan Felisa",
        "Darmadi Karjanto Putro",
        "Darmansjah Darsono",
        "Darmawansjah Setiawan",
        "Darminto",
        "Darminto Hartono",
        "Darmo Suwito Barwin",
        "Darmoseputro",
        "Darwin Leo",
        "Darwin Silalahi",
        "Darwin Soegiatto",
        "Darwin Sutanto",
        "Daswi Rayawang",
        "David Alexander Yuwono",
        "David Kristian",
        "David Kuchenbecker",
        "David Myles Falkner",
        "David Nico Sutanto",
        "David Pierre Michael Bakker",
        "David Salim",
        "David Widjaja",
        "David William Donaldson",
        "David William Magson",
        "Debby Febriany Gunawan",
        "Deborah Kent Janawati",
        "Deddy Harijanto Sudarijanto",
        "Dedie Suherlan",
        "Dedy Rochimat",
        "Dendy Kurniawan",
        "Denise Tjokrosaputro",
        "Denny Lim",
        "Denny Rahardja",
        "Denny Suryadinata",
        "Denny Wijaya",
        "Deny Juliarto",
        "Dermawan",
        "Devi Tri Asmarasari",
        "Devie Hendrastiti Darmawan",
        "Devin Wirawan",
        "Devy Prasetyo Yuwono Ang",
        "Dewi Garlina Sari",
        "Dewi Indrajani Alimwidjaja",
        "Dewi Kencanawati Natawidjaja",
        "Dewi Natalia Lim",
        "Dewi Nilka Sari",
        "Dewi Novianawati",
        "Dewi Suryati Liauw",
        "Dharma Tjitra Widjaja",
        "Dharmadi Budiman",
        "Dharmawandi Sutanto",
        "Dharsono Hartono",
        "Diah Soemedi",
        "Dian Muljani Soedarjo",
        "Dian Sumeler",
        "Diana Husein",
        "Diana Sastrajaya",
        "Dick Leitch",
        "Dicky Herman",
        "Dicky Kurniawan",
        "Dicky Tjokrosaputro",
        "Dicky Yordan",
        "Didi Ferdinand Korompis",
        "Didit Abdurachman Rustandi",
        "Didit Budijarto",
        "Dina Eldelina Pow",
        "Diniwati",
        "Dino Koeshandery",
        "Diono Nurjadin",
        "Dixon Koesdjojo",
        "Djajadi Djaja",
        "Djajadinata Hardjono",
        "Djamaluddin Tanoto",
        "Limiwaty Lie",
        "Djan Faridz",
        "Djatmiko Tedjo",
        "Djauhara Faizal",
        "Djerisin Kuesar",
        "Djie Tjian An",
        "Febe Maryanti Wirjadi",
        "Djohan Is Hardjo",
        "Djohan Tjiunardi",
        "Djoko Soegiarto Tjandra",
        "Djoko Kartono",
        "Djoko N. Labbaika",
        "Djoko Nirmala Labbaika",
        "Djoko Soesanto Gusti",
        "Djoni Muchsin",
        "Djoni Rion Gui",
        "Kusnadi Gui",
        "Djoni Sukohardjo",
        "Djonny Koesoemahardjono",
        "Djuana Sulestio",
        "Djuffan Achmad",
        "Djumharbey Anwar",
        "Djuniar Tunggal",
        "Doddy Agustiawan Tjahjadi",
        "Dodi Suhartono Abdul Kadir",
        "Dody Lukito Hendrokusumo",
        "Dolly Periagutan Pulungan",
        "Dominique Gallamnn",
        "Don MacDonald",
        "Doni Irawan",
        "Donny Imam Priambodo",
        "Donny Yoesgiantoro",
        "Doreen Sim",
        "Dorys Setiawati Herlambang",
        "Douglas Vincent Tingey",
        "Dr. Hmnm Hasyim Ning",
        "Dr. R. Soeparmadi",
        "Dr. Cheam Soon Tee",
        "Dr. Darmadi Goenawan",
        "Dr. Johnny Goenawan",
        "Dr. Kahar Tjandra",
        "Evy Tjandra",
        "Nancy Tjandra Muljadi",
        "Dr. Pudji Witomo",
        "Dr. Aryanto Agus Mulyo",
        "Dr. J. B. Netyaka",
        "Dunn Fa Chong",
        "Dwiarti Widiyani",
        "Eddi Sugiardi",
        "Eddie Sudijono",
        "Eddy Daud",
        "Eddy Halim",
        "Eddy Handoko",
        "Eddy Herman",
        "Eddy Hussy",
        "Eddy Iskandar",
        "Eddy Kusnadi Sariaatmadja",
        "Sofie Widjaja Sariaatmadja",
        "Eddy Pramono",
        "Eddy Purwanto Lim",
        "Eddy Setiawan",
        "Eddy Sindoro",
        "Eddy Susanto",
        "Eddy Sutandinata",
        "Eddy William Katuari",
        "Eddy Winata",
        "Eddyanto Hadisurjo",
        "Ratna Kurniati Bahana",
        "Edgardo Abelarde Tinsay",
        "Edgardo Eloy Diaz Falconet",
        "Edhie Hardjanto",
        "Edi Firmansyah",
        "Edianto Prasetyo",
        "Edo Djunaydi",
        "Edoardus Ardianto",
        "Edward Ang",
        "Edward Magnus Lang",
        "Hans Jurgen Kaschull",
        "Kartini Herawati Lang",
        "Edward Stephanus Djauhari",
        "Edwin Mohtar",
        "Edwin Muchtar",
        "Edwin Soeryadjaya",
        "Edwin Sugiarto",
        "Edy",
        "Edy Kosasih",
        "Edy Kusnadi",
        "Edy Susanto",
        "Edy Suwarno",
        "Efendi Boedhiman",
        "Effendy Husin",
        "Efrem Wardhana",
        "Eiffel Tedja",
        "Eka Sinto Kasih Tjia",
        "Eko Budianto",
        "Eko Prasetyo Ang",
        "Eko Purnomo",
        "Eko Suharto",
        "Eko Sukamto",
        "El Beatrice",
        "Eliani Johan",
        "Eliezer Nugroho Tjandrakusuma",
        "Elisabet Lay",
        "Elisabeth Lintje",
        "Elisabeth Magdalena",
        "Elizabeth Januarti W",
        "Elizabeth Jayne",
        "Elizabeth Sindoro",
        "Elizabeth",
        "Alicia",
        "Denise",
        "Michelle",
        "Elke Camillia Kurniawan",
        "Elline Yohan Yau",
        "Elly Koeswandia Tjokronegoro",
        "Elly Lestari Adiutama",
        "Elly Nurlaila Hutabarat",
        "Elly Soepono",
        "Elmursil Moenzir",
        "Elsa Djauhari",
        "Elvina Jonas Jahja",
        "Elvira Pudjiwati",
        "Emi Sukiati Lasimon",
        "Emil Abeng",
        "Emily Stephana Djauhari",
        "Emily Waty Setiawan",
        "Emmy Damayanti",
        "Emy Harjono",
        "Andres S. Magbitang jr",
        "Endah Sulistyorini Himawan",
        "Endang Soertikanty",
        "Endang Sugiarti",
        "Endang Susila Budi",
        "Endang Triningsih",
        "Endro S. Wahono",
        "Endy Suryokusumo",
        "Enny Lukitaning Diah",
        "Enny Soegiarto",
        "Enny Trang",
        "Entario Widjaja Susanto",
        "Era Helvani",
        "Eric Hardono Tirtajasa",
        "Erick Djuwadi",
        "Erick Thohir",
        "Erics Yoshawirja",
        "Erik Setiawan",
        "Erika Debora Djauhari",
        "Erlina Ongoredjo",
        "Erlina Ongsoredjo",
        "Erly Tandjung",
        "Erna Widyastuti",
        "Ernawati",
        "Erni Gunawan",
        "Ernitha Halim",
        "Erric B. Wibowo",
        "Ervin Wijaya",
        "Shiany Angsana",
        "Erwin Aksa",
        "Erwin Budisantosa",
        "Erwin Ciputra",
        "Erwin Gunawan",
        "Erwin Indra Hamid",
        "Erwin Sasunto",
        "Wiwiek Kwedarisman",
        "Erwin Tunggul Setiawan",
        "Ery Yunasri",
        "Esther Riawaty Hari",
        "Eugene Trismitro",
        "Eunice Meriati Satyono",
        "Eva Berliana Rosway",
        "Evelyn Luciana Soeyapto",
        "Evert Jimmy Lengkong",
        "Evi Hamdani",
        "Evi Wikarsa",
        "Evie Raviana",
        "Ewik Hendri",
        "Gunawan Endi",
        "Jotaro Kujo",
        "Wantonio",
        "Cloud Strifer",
        "F. Franky",
        "Fabian Gelael",
        "Fadjar Endranto",
        "Fahmi Babra",
        "Fahmi Idris",
        "Fahyudi Djaniatmadja",
        "Faisal Panggabean Law Firm",
        "Faisol Soleh Masjkoer",
        "Faiz Shahab",
        "Faizan Abdul Rahan",
        "Fan Chiang",
        "Teng-Chang",
        "Farah Liza",
        "Farouk Rais",
        "Fauzi Ezeddin",
        "Fauzi Jahja",
        "Fauzi Jurnalis",
        "Febrina Sari Bak",
        "Feilie Sulestijani",
        "Felianah Soetemo",
        "Fendi Santoso",
        "Fenza Sofyan",
        "Ferry Tenacious",
        "Fida Unidjaja",
        "Fifi Indra",
        "Finney Henry Katuari",
        "Fiona Adeline Sutanto",
        "Firdaus Siddik",
        "Firman Matondang Silalahi",
        "Fitri Wiriasari",
        "Florence James",
        "Florence Wanamurti",
        "Flores Samudro",
        "Foe Siat Khiun",
        "Fong Felix",
        "Fong",
        "Fonny Tedjajadi",
        "Foronkid Gunawan",
        "Francisca Citrasari",
        "Franciscus Xaverius Hardianto Tjondro",
        "Frank Taira Supit",
        "Franky Widjoyo",
        "Frans Limas",
        "Fransiscus Antonius S.A.",
        "Fransiskus Budhinata",
        "Fransisous Iwo",
        "Freddy H. Suryadiharja",
        "Freddy Ignatius Katuari",
        "Freddy Sumartono Santoso",
        "Freddy Sutjipto",
        "Freddyanto Tirtadjaja",
        "Fuad Segayir Alkatiri",
        "G. Lal Agrawala",
        "Gahet Loengara Ascobat",
        "Gahral Sjah",
        "Gaitini Tjokrosaputro",
        "Gan Boot Lian",
        "Gan Chooi Yang",
        "Gandhi Bend",
        "Ganesh Chander Grover",
        "Gareth Joh Lewis",
        "Garibaldi Thohir",
        "Gary Dino Ridwan Sjah",
        "Gary Neal Christenson",
        "Gary Phair",
        "Gatot Kariyoso Wiroyudo",
        "Geeta M. Mirpuri",
        "Gemilang Investama",
        "Gen Sik Tjin Tan",
        "Geoffrey David Simms",
        "George Christoph Robert Spath",
        "George Nicolas Simanjuntak",
        "George Setiyadi",
        "Gerald Rossi",
        "Gerry Aubry",
        "Gerry Prawira Saputra Tjong",
        "Gesang Budiarso",
        "Ginawan Chondro",
        "Gino Junior Korompis",
        "Giovani Maria Ekaputra Suhari",
        "Yasmin Stamboel Wirjawan",
        "Gladys Kiong",
        "Glenn Timothy Sugita",
        "Go Sek San",
        "Go Siauw Hong",
        "Go Sik Ying",
        "Go Sri Hartati",
        "Godefridus Tampubolon",
        "Goh Lay Ling",
        "Goh Tie Sin",
        "Graham Daniel Fogarty",
        "Grant McArthur",
        "Grant Moon-Tae Kim",
        "Gregorius Petrus Aji Wijaya",
        "Gregory Campbell Hinchlife",
        "GT Asia Pacific Funds Management Limited",
        "Guat Tjing Thio",
        "Gunardi Frans Fong",
        "Gunawan Gusti",
        "Gunawan Jusuf",
        "Gunawan Santoso Gwie",
        "Gunawan Subagio",
        "Gunawan Sucahijono Tjoa",
        "Gunawan Suteja",
        "GW Franklin Hall",
        "H. Sonny Wibisono Widjanarko",
        "H.I. Made Sadha Ardiana",
        "Hadi Gunawan",
        "Hadi Lukman",
        "Hadi Suginawan",
        "Nurmalasari Suginawan",
        "Hadidarma Kosasih Kho",
        "Hadinata Widjaja",
        "Hadysugani Hoshi",
        "Hajato Darsono",
        "Halifah Sunjata",
        "Halim Podiono",
        "Halim Setiabudi Wijono",
        "Han Hai Thon",
        "Han Jung Kuk",
        "Handaja Susanto",
        "Handi Gunawan",
        "Handojo Santosa",
        "Handoko Anindya Tanuadji",
        "Handoko Susilo",
        "Handoyo Sutanto",
        "Handrie Wirawan",
        "Handy Sunardio",
        "Hanny Suprayogi",
        "Hanny Sutanto",
        "Hans Maramis",
        "Hans Moelyadi",
        "Hansen Suryadi",
        "Hanson Ramli",
        "Hardy Woosnam",
        "Hari Raharta",
        "Hari Widodo",
        "Hariadien Ratmawati Soeprapto",
        "Harianto Solichin",
        "Harianto Peh",
        "Harijanto Koesdjojo",
        "Haris",
        "Hariyanto Wijaya Sarwono Lim",
        "Harjanto Kusuma Halim",
        "Lisa Ambarwati Dharmawan",
        "Harjoseno",
        "Harmiono Judianto",
        "Harris Lasmana",
        "Harry Haslett",
        "Harry Herjanto",
        "Harry Nugroho Prasetyo",
        "Harry Soeria",
        "Harry Susanto",
        "Harry Suwignjo",
        "Hartadi Angkosubroto",
        "Harto Djojo Nagaria",
        "Hartono Gunawan",
        "Hartono Sundoro Hosea",
        "Haruhiko",
        "Harun Ibrahim Tajuddin Nur",
        "Hary Djaja ",
        "Ratna Endang Hartatiek",
        "Haryadi Kumala",
        "Haryetti",
        "Haryono Winarta",
        "Hasan Aula",
        "Nina Koswandi",
        "Hasan Dali",
        "Hasan W. W. Krisno",
        "Hasnuryani Sulaiman",
        "Haston Limardo",
        "Hastuti Sulistio",
        "Hawanto Hartono",
        "Hazriyandi",
        "Heindrix Liauw",
        "Helen Turtan Setiawan",
        "Helen Wijaya Ong",
        "Helmut Paasch",
        "Helyuzar",
        "Hengky Kunta Adjie",
        "Hendarta Atmadja",
        "Hendra Alamsjah",
        "Hendra Basoeki",
        "Hendra Harjadi",
        "Hendra Koesnadi",
        "Hendra Liem",
        "Hendra Nagaria",
        "Hendra Nova Syamsu",
        "Hendra Soegiarto",
        "Hendra Tjahyawati",
        "Hendra Tjoa",
        "Hendra Wijaja",
        "Tang Linawaty",
        "Teddy Widjaja",
        "William",
        "Silvia",
        "Hendra Wirajang",
        "Hendrik",
        "Hendrik Hartono",
        "Hendrik Suhardiman",
        "Hendrik Tanojo",
        "Hendrik Tee",
        "Hendro Guwanda Sutandi",
        "Hendro Santoso Gondokusumo",
        "Hendro Setiawan",
        "Hendro Tjokrosetio",
        "Hendry Lesmana",
        "Hendy Rusli",
        "Heng Ijat Hong",
        "Hengki Sovian",
        "Hengky Tenacious",
        "Henking Wargana",
        "Henky Suwignjo",
        "Henny Harmani Wirjosoekarto",
        "Henny Hartady",
        "Henny Kentjanawati Natawidjaja",
        "Henny Kusumawati Tanuhardja",
        "Henny Purnamawati",
        "Henny Santoso",
        "Henny Victoria",
        "Henoch Pradhana",
        "Henrianto Kuswendi",
        "Henrik Antoni Jie",
        "Diana Purnamasari Go",
        "Adi Janitra",
        "Henry Halomoan Sitanggang",
        "Henry Hartono Go",
        "Henry Jahja",
        "Henry Kurli",
        "Lin Konggui",
        "Henry Leo",
        "Henry Liem",
        "Henry Pribadi",
        "Henry Rudy Zaini",
        "Hendry Supanini",
        "Henry Susilowidjojo Njoo",
        "Henry Suwignjo",
        "Henry Wargana",
        "Henry Widjaya",
        "Herdin Syafari",
        "Herik Antoni Jie",
        "Herlina",
        "Herlinah Soetemo",
        "Herline Goenawan",
        "Herman Afif Kusumo",
        "Herman Gozali",
        "Herman Iskandar",
        "Khoe Ay Hwa",
        "Seraphine Volkani Iskandar",
        "Herman Karmana",
        "Herman Moeliana",
        "Herman Nagaria",
        "Herman Wijaya",
        "Yuliana Kusno",
        "Lenny",
        "Rudy",
        "Joni Wijaya",
        "Herman Y. S. Gunawan",
        "Hermani Soeprapto",
        "Hermansjah Tamin",
        "Hermanto Tangkau Adrian",
        "Hermijanto Toto",
        "Herry Mirza Putera",
        "Herry Wibowo",
        "Heru Hidayat",
        "Heru Soesanto Gusti",
        "Heru Sucahyo",
        "Herumanlo Zaini",
        "Hesti Femi Nugraheny",
        "Hesye Silya Mamesah",
        "Hetty Heryati Sumantri",
        "Hetty Indrakasih Soetikno",
        "Hilary Richard Bolton",
        "Hilda Noveda Kaliman",
        "Hilmi Panigoro",
        "Hilton King",
        "Hilton R. King",
        "Himawan Surya",
        "Hindarta Sanjaya",
        "Hindarto Budiono",
        "Hindarto Suhardjo",
        "Hioe Isenta",
        "Ivy Lianawati",
        "Hiramsyah Sambudhy Thaib",
        "Hiswara Natawindjaja",
        "Ho Mie Ling",
        "Ho Sze Wah",
        "Hoediono Kweefanus",
        "Hoesen Gunawan",
        "Honey Angkosubroto",
        "Hong Usman Effendy",
        "Horas Chu Naga",
        "Hosea Hadeli",
        "Hotman Naiborhu",
        "Houston Jusuf",
        "Hubertus Setiyadi",
        "Hudi Janti",
        "Hunarti Gosal",
        "Husin Chandra",
        "Husin Sariman",
        "Dewi Ngadiman",
        "Husin Suliawan",
        "Husni Muchtar",
        "Husodo Angkosubroto",
        "Hutabarat",
        "I. Gusti Ngurah Adi Suputra",
        "I. Made Djendra",
        "I. Nengah Bagiada",
        "I. Nyoman Djintji",
        "I. Wayan Arya",
        "I. Goesti Ben Kel Bagoes Oka",
        "Ian Donald Macaulay",
        "Ibrahim",
        "Ibu Rahmawaty",
        "Ichsan Rizal",
        "Ichsanuddin Noorsy",
        "Ida Bagus Made Putra Jandhana",
        "Ida Budisusetyo",
        "Ie Kian Tjoan",
        "Ie Mila Setiawaty",
        "Ignanto Sandjojo",
        "Ignatius Joe Budiman",
        "Ignatius Toni Gunawan",
        "Iing Yoshawirja",
        "Ima Endang Prayanti Garibaldi",
        "Ima Tjahjadi Tjhang",
        "Imam Muhadi Rowi",
        "Iman Tamin",
        "Imelda Dharma",
        "Ina Irena Jonas Jahja",
        "Inayat Ali Badruddin",
        "Inda Aryanti Imanto",
        "Indah Djuita Tjatursari",
        "Indahwaty Hartono",
        "Indawan Saputra Hatta",
        "Indawati",
        "Inder Singh",
        "Indra Gunawan",
        "Indra Gunawan Wonowidjojo",
        "Indra Makmur",
        "Indra Muliadi Sugiharto",
        "Indra Widjaja",
        "Indrajaty Hadiwardojo",
        "Indrawati Sampoerna",
        "Indriani Harsono",
        "Indriena Yudhayanti Basarah",
        "Indro Wibowo",
        "Ingrid Wilianto",
        "Ir. Danny Walla",
        "Ir. Hagianto Kumala",
        "Ir. Rudyanto Hardjanto",
        "Irawan Hadikusumo",
        "Irawan Kurniadi Tjandra",
        "Irawan Sutandinata",
        "Irawan Widjaja",
        "Irene Maya Hambali Ishak",
        "Irene Susanto Adikoesoemo",
        "Irene Tedja",
        "Iriawan Suharyanto",
        "Irma Mirzanti",
        "Iroshita Arsyafira",
        "Irsanto Ongko",
        "Irvinia Megawati Saddak",
        "Irwan Atmadja Dinata",
        "Irwan Hermanto",
        "Irwan Santoso Chandra",
        "Irwan Siregar",
        "Irwandy Ma Rajabasa",
        "Isenta Hioe",
        "Ishak Sumarno",
        "Iskandar Tanuwidjaja",
        "Ismail Hirawan",
        "Istini Siddharta",
        "Istini Tatiek Siddharta",
        "Itjendri Suitono Thio",
        "Ivan Budiono",
        "Ivan Setiawan Tan",
        "Ivantara Dviyudha",
        "Ivonny Budiono",
        "Iwa Sewaka",
        "Iwan Dewono Budi Juwono",
        "Iwan Hardja",
        "Iwan Margana",
        "Iwan Rosadi Widyapranolo",
        "Iwan Ruwiyadi",
        "Iwan Samsuddin",
        "Iwan Valiant Joesoef",
        "Marwan Arie Joesoef",
        "Nurfadh Subhan Joesoef",
        "J. C. Gosa",
        "Jackson Chu",
        "Jacky Afandi",
        "Jacky Soerya Santoso",
        "Jacob Antung Kang",
        "Jacob Soetoyo",
        "Jacobus Busono",
        "Jacobus Busono Prawiroredjo",
        "Jacqueline Tjahjadi",
        "Jacub Johannes The",
        "Jahja Santoso",
        "Johana Poedjokerto",
        "Jahjaa Soetoyo",
        "Jajat Priatna Purwita",
        "James Budiono",
        "James C. Haebig",
        "James Eric Zaini",
        "James Kallman",
        "James Preston Truesdell",
        "James Rachman Adjimin",
        "James Steven Kallman",
        "James T. Riady",
        "James Thomas Henry Arthur",
        "James Tjahaja Riady",
        "Jamin Soetoyo",
        "Jamin Tjandra",
        "Jan Adam Tangkilisan",
        "Jan Triana Johanes",
        "Yuliana Johanes",
        "Windy Marlina",
        "Omar Azhari",
        "Nurdin Hasjim Johanes",
        "Oktavia Dewi Tirta",
        "Janni",
        "Jansen Wiraatmaja",
        "Janti Jahja",
        "Jap Carmen",
        "Jap Hartono",
        "Santy Muljawana",
        "Jap Johanes",
        "Jap Soegiono",
        "Jason James Raymond",
        "Jayanti Sari",
        "Jeannie Widjaja",
        "Jeffery Freshen Sihombing",
        "Jeffery Koes Wonsoo",
        "Jeffrey Hartono",
        "Jeffrey Iuwena",
        "Jeffrey K. Wonsono",
        "Jeffrey Koes Wonsono",
        "Jeffrey Sugianto",
        "Jendrawasih Jenni",
        "Jeniawati",
        "Jennie Widjaya",
        "Jenny Elisabeth RG",
        "Jenty",
        "Jeremy David Kemp",
        "Jessy Vishamkar Adnani",
        "Jialipto Jiaravanon",
        "Jim Truesdell",
        "Jimmy Budhi",
        "Jimmy Budiarto",
        "Jimmy Hartono Lie",
        "Jimmy Henricus Kurniawan Laihad",
        "Jimmy Namara",
        "Jimmy Samantha",
        "Jimmy Suryanto Budhi",
        "Jimmy Tjahjanto",
        "Jimmy Welianto Siauw",
        "Jimmy Ziepo Setiawan",
        "Jio Tien Carolyna",
        "Jiohan Sebastian",
        "Jo Andreson Wiharjo",
        "Jo Gasyanto",
        "Jo Liat Tjiang",
        "Jo Souw Koan",
        "Jo Tjin Khoen",
        "Joachim U. Rohn",
        "Joachim Ulrich Rohn",
        "Joachim V. Rohn",
        "Jocelin Yohan Yau",
        "Jodi Haryanto",
        "Joe Su Fun",
        "Joeliardi Sunendar",
        "Joesril Hainim",
        "Jogi Hendra Atmadja",
        "Johan Alexander Supit",
        "Johan Arifkaja Adi Lesmana",
        "Johan Soedibjo",
        "Johan T. Gilbert",
        "Johan Tandean",
        "Johanes Herkiamto",
        "Johanes Gunawan",
        "Johanes Kennedy Aritonang",
        "Johanes Susilo",
        "Johanes Tang Widjaja",
        "Johannes Goenawan",
        "Johannes Halim",
        "Johannes Oentoro",
        "Johannes Setijono",
        "Indriyati",
        "Johannes Tanuwijaya",
        "John Kosasih",
        "John Franklin",
        "John Gordon McFadzien",
        "John Hugh Lester",
        "John Joseph Franklin",
        "John Todo Bonner",
        "John Williem Vanderwal",
        "Johnlee Mailoa",
        "Johnnie Hermanto",
        "Johnny",
        "Johnny Wiriawan",
        "Johnson Williang Sutjipto",
        "Johny Lisangan",
        "Johny Surjana",
        "Joice",
        "Joko Himawan",
        "Paul Himawan",
        "Jonas Jahja",
        "Joni Yoesoef",
        "Jopie Widjaja",
        "Joppy Robert Saerang",
        "Jos Parengkuan",
        "Jos Winata Wihardja",
        "Jose R. Hanna",
        "Josef Indra Njoman",
        "Josep Lay",
        "Josep Susanto Kiswandono",
        "Joseph Dharmabrata",
        "Joseph Donald Charles Buddy",
        "Joseph Tjakra",
        "Josephyne Widjaja",
        "Joso Ramli",
        "Jovanka Mardova",
        "Joyce Handajani",
        "Jozef Darmawan Angkasa",
        "Juanda Lesmana Lauw",
        "Juandy Wijaya",
        "Judca Herlina Hansoehardi",
        "Judi Gunawan",
        "Juliana Kusnandar",
        "Juliana Ong Pei I.",
        "Julianna Yohan",
        "Juliati Widjaja",
        "Juliati Widjojo",
        "Juliawati Budiman",
        "Julie Mulya Jiauw",
        "Junanda Syarfuan",
        "Juni Setiawati Wonowidjojo",
        "Junita Ciputra",
        "Junius Wijaya",
        "Junty",
        "Junus Jen Suherman",
        "Junus Siswadi",
        "Jusak Hadi Wardojo",
        "Justian Suhandinata",
        "Justin Barney Goff",
        "Justin Breheny",
        "Justo Padilla Nestro",
        "Jusuf",
        "Jusuf Handri Rachmantio",
        "Jusuf Heryanto",
        "Jusuf Salman",
        "Jusuf Tanuwidjaja",
        "Jusup Budihartono Prajogo",
        "Jusup Susanto Djunaidi",
        "Juwita Lianty Suandi",
        "Jyoti Lekhraj Budhrani",
        "K. Melbourne Breau",
        "K. P. Irwan Kartawijaya",
        "Kakan Sukanda Dinata",
        "Kalim",
        "Kam Lie Giok",
        "Kama Putra Kusdianto",
        "Kaman Halim",
        "Kamlesh Ishwardas",
        "Kang Aries Fuksar",
        "Kang Rita Sadeli",
        "Song Wen Shyu",
        "Kanisha Sunil Mirpuri",
        "Kardaya Warnika",
        "Kardja Rahardjo",
        "Karta Wiguna",
        "Kartini Fahmi Idris",
        "Karuna Murdaya",
        "Kasiviswanathan Prakash",
        "Katharina Wihardja",
        "Katini Dewi",
        "Katleen Yangrikho Gui",
        "Kazan Gunawan",
        "Ken Leksono Sedianto",
        "Ken Ng",
        "Kendra Soegandha",
        "Kenneth R. Wynn",
        "Kezia Putri Aprilya Kusdianto",
        "Khairul Saleh",
        "Khou Lim Ngo",
        "Kiki Barki",
        "Kiki Kiftiah",
        "Kiki Sutantyo",
        "Kim Doo Young",
        "Kim Sung Kook",
        "Kimberly Ananto",
        "Kimin Tanoto",
        "Kindarto Kohar",
        "Kirk D. Evans",
        "Kirk David Evans",
        "Kitty Joantina Wulanda",
        "Kitty Tjioe",
        "Kiyomi Sato",
        "Ko Rudy Oetomo",
        "Kokarjadi Chandra",
        "Koko Poernomo Santoso",
        "Kokos Leo Lim",
        "Kompleks Perkantoran",
        "Kris Widjojo",
        "Krishan Kulmar Ralhan",
        "Krishnan Sjarif",
        "Krisnadi Gautama",
        "Krisno Abiyanto",
        "Soekarno",
        "Kristanto Wibowo Siswanto",
        "Kristina Minto",
        "Kumalasari Tjiong",
        "Kurniati Phan",
        "Jusuf Budi Wijoto",
        "Kurniawan Nurdin Karim",
        "Kusdianto Soewarno",
        "Kusnadi Budiman",
        "Kusnan Kirana",
        "Kusuma Hadi Soetemo",
        "Kusumawati",
        "Kusumo Abujono Martorejo",
        "Kusumo Purwanti Dewi",
        "Kwee Suo Chie",
        "Kwok Moi Moy",
        "Laksamana Sukardi",
        "Lakshmi Harris Lasmana",
        "Laksmi Tratiwi Dallamore",
        "Lam Mang Ying",
        "Lam Toi Lai",
        "Lambertus Nuryono",
        "Lambertus Somar",
        "Lanasari Halim",
        "Lanny Lanawaty",
        "Lanny Tanzil",
        "Lanny Widjajanti",
        "Lao Rusming",
        "Lauw Samuel Lawrence",
        "Lawrence Barki",
        "Lay Sioe Ho",
        "Le Purna Harjani",
        "Leda Magdangal Tamin",
        "Lee Chuck Soo",
        "Lee Yick Cheung",
        "Leman Hadi Soetemo",
        "Lenny Wijaya",
        "Leny Anwar",
        "Leny I. Wangsawidjaja",
        "Leonardus Eko Daru Lumadyo",
        "Lestariono",
        "Letty Johan",
        "Levi Octavia Soewarna",
        "Lianawati Setyo",
        "Liauw Sumiati",
        "Lidwina Lindawati Kartiko",
        "Lie Sie Giem",
        "Lie Soemarli",
        "Lie Tjauw Mian",
        "Lie Tjin Ming",
        "Liem Hadi Mualim",
        "Liem Johan Halim",
        "Liem Kong Shiung",
        "Liem Sin Huang",
        "Lies Kusumawati",
        "Lijatini Setiono",
        "Likin Handoko",
        "LiLi Ashari",
        "Liliana Budi Santoso",
        "Willy Gunawan",
        "Liliana Wibisono",
        "Liliawati Rahardjo",
        "Lily Ciarensia Tjia",
        "Lily Lawandra",
        "Lily Marjani Pribadi",
        "Lily Solaiman Sutantyo",
        "Lily Tamin",
        "Lily Yuliani Halim",
        "Lilyani Tanoko",
        "Lilys Tjiawi",
        "Lim Arie Sasmita",
        "Lim Eng Khim",
        "Lim Fie Tjong",
        "Lim Lys Erty",
        "Lim Soon Huat",
        "Lim Tjung Luong",
        "Limanto",
        "Yu-Cheng",
        "Lina Gunawan",
        "Lina Harjanti Latif",
        "Lina Kurniawan",
        "Lina Soegiharto Leo",
        "Linawidjaja Kusprajudi",
        "Linda Hakim",
        "Linda Lauw",
        "Linda Marlina Isatyawan",
        "Linda Ng",
        "Linda Rachmat",
        "Linda Sidharta",
        "Linda Tanuwiradjaja",
        "Linda Tjahja",
        "Lindawaty Hartono",
        "Lisa Mardiani Gunawan",
        "Lisa Sundoro Hosea",
        "Lisa Widjaja",
        "Lisawati Soegiharto",
        "Lista Adriani",
        "Listyani Setijawati Sidik",
        "Loa Djin Sui",
        "Loa Sui Hong",
        "Lovri Ricarda",
        "Lucas",
        "Lenny Patricia Halim Liem",
        "Lucia Mogi",
        "Lucia Sungkoro",
        "Lucky Tjahaja Diputra Prawiro",
        "Lukas Masehi",
        "Lukman Ahmad Mahfoed",
        "Lukman Hakin",
        "Lukman Herry Latip",
        "Lukman Tirtaguna",
        "Lum Weng Loy",
        "Lunardi Basuki",
        "Sasongko Basuki",
        "Basuki",
        "Lusi Murniati Gunawan",
        "Lusi Windayati",
        "Lys Erna Ontjeng",
        "M. A. Ismail Ning",
        "Madampath Sathibal Menon",
        "Made Oka Masagung",
        "Maggie",
        "Mahesa Alit Pramesty",
        "Maiko Kawano",
        "Makarim",
        "Maly Widoyo",
        "Marcella Magdalena",
        "Marcellus Charles Colondam",
        "Marcellyna Junita Widjaja",
        "Marco Baldini",
        "Margareth Maria Regina Budhiparama",
        "Margaretha Natalia Widjaja",
        "Maria Karmila",
        "Marilyn Caracas",
        "Mario Christy",
        "Mario Satya Pratomo",
        "Mark Patrick Hanusz",
        "Markun",
        "Markus Parmadi",
        "Marluce Tio Indriati Santoso",
        "Marten Liu",
        "Martin Wijaya Ng",
        "Martina M. Sukwikaimono",
        "Martinus Arief Limandoko",
        "Marvin C. S. Yong",
        "Maryati Benniardi Imanto",
        "Masayu Pangestu",
        "Mathilda Stephanie",
        "Matthew S. Deayton",
        "Maxymilian Adelberd",
        "Meena",
        "Megawati Setiadi",
        "Mei Ing",
        "Meigawaty Soejatno",
        "Meiliana Widjaja",
        "Meiriaty Soetoyo",
        "Meity Subianto",
        "Meizar Suyardi",
        "Melina Jonas",
        "Melisa Patricia Tanoko",
        "Melissa Ong",
        "Melly Kristanti",
        "Melvin",
        "Mende Sulinadi",
        "Meranti Handajani Serad",
        "Merry",
        "Metta Margaretha Murdaya",
        "Miana Dwilasmini Sudwikatmono",
        "Michael D. Twomey",
        "Michael Dharmawan Euslim",
        "Michael Gan",
        "Michael Goenawan",
        "Michael Jackson Purwanto Widjaja",
        "Michael Mary Mackay Seward",
        "Michael Rusli",
        "Michael Seabrook",
        "Michael Steven",
        "Ingrid Kusumodjojo",
        "Michael Tjahjadi",
        "Michael Twomey",
        "Michael Wijaya Goutama",
        "Micheal Tjahjadi",
        "Michel Vicky Tumiwang",
        "Michelle Tjokrosaputro",
        "Mieke Santosa",
        "Milany Terianto Luwena",
        "Mimin Aminah",
        "Minny Riady",
        "Mintardjo Halim",
        "Mira Savira",
        "Mirah Amiria Adhyaksa",
        "Miranda Tedjasaputra",
        "Miranti Handajani Serad",
        "Mochamad Adnan",
        "Mochamad Rais",
        "Mochammad Anwar",
        "Mochtar Riady",
        "Moernoto Reksonegoro",
        "Mohamad Noer",
        "Mohamad Abdullah Jasin",
        "Dewi Kam",
        "Mohamad Iskandar",
        "Mohammad Hidayat Hasan",
        "Mohammad Lendi Basarah",
        "Mohammad Mas Pendi Soleh",
        "Mohammad Noah Haji",
        "Mohan N. Mirpuri",
        "Mohit Ramchand Vaswani",
        "Monalita Kardono Soegiarto",
        "Monica Yoanita Octavia",
        "Morgan Tjoe",
        "Motinggo Soputan",
        "Mr. Arifin Yohan",
        "Mr. Aris Sunarko",
        "Mr. Burhansjah",
        "Mr. Koh Tji Beng",
        "Mr. Liem Henry",
        "Mr. Marimutu Siniran",
        "Mr. Nono Fadjartyassasono Padmodimuljo",
        "Mr. Ulian Napsiah",
        "Mr. Welly",
        "Mr. William Goenawan",
        "Mr. Eddy Goenawan",
        "Mr. Salim Aziz Mochdar",
        "Mrs. Josephine Budi Santoso",
        "Mrs. Lina Ovani",
        "Mrs. Masiana Wijaya",
        "Mrs. Theresia Noerpeni Padmodimuljo",
        "Ms. Affin",
        "Ms. Rohani Indahsi",
        "Ms. Taxes",
        "Ms. T.Handayani Andokho",
        "Muddai Madang",
        "Mugijanto Sugijono",
        "Muhammad Agus",
        "Muhammad Aksa Mahmud",
        "Muhammad Alatas",
        "Muhammad Andre Pasha Djuanda",
        "Muhammad Ikbal",
        "Mulianto Api Tanaga",
        "Mulianto Tanaga",
        "Muljadi Budiman",
        "Muljadi Irawan",
        "Muljana Husodho",
        "Tintje Jusran",
        "Fransisca Haller",
        "Andreas Husodho",
        "Danni Arton",
        "Mulyadi Anggono",
        "Munkley Christopher James",
        "Murdaya Widyawimarta",
        "Mustiko Saleh",
        "Mustofa",
        "Myrna Esther Contreras De Navarro",
        "Myrna Putri Pribadi",
        "Na Na",
        "Nam Yong Hwa",
        "Nancy Narsis Runtuwene",
        "Nancy Urania Rachman Latief",
        "Nani Indraswati Alimwidjaja",
        "Nanik Santoso",
        "Naresh Kumar Modi",
        "Nasir Saleem Haji",
        "Natalie Ong",
        "Natalie Tjahjadi",
        "Nathalia Setiawan",
        "Nazamudin Latief",
        "Nazarudin Kiemas",
        "Nestor Padilla",
        "Ng Kee Yeok",
        "Ng Soat Go",
        "Ng Tje Suang",
        "Ngadimun",
        "Ngu Hew Tak",
        "Ni Made Jati",
        "Nia Soniati Wityasmoro",
        "Nicholaas Bernardus Tirtadinata",
        "Nicholas James Graham",
        "Nico Krisnanto",
        "Nigel Brett Eaton",
        "Niko Listya Prabowo Se",
        "Nila Fatina",
        "Nilayanti",
        "Nini Djajasaputra",
        "Niniek Haryani",
        "Ninik P. Nathan",
        "Nio Yantony",
        "Nixon Jacobus Silfanus",
        "Norbert Alois Meixner",
        "Nordiansyah Nasri",
        "Nova Chandra",
        "Nova Negara Silaban",
        "Nova Yudhanto Mugiyanto",
        "Novi Ariyunida Dharma",
        "Novi Nenolaswaty",
        "Noviani Eka Susanto",
        "Nugraha Tirtanata",
        "Nugroho Halim Wijaya",
        "Nur Zain",
        "Nurbaiti",
        "Nurochim",
        "Nursalim Podiono",
        "Nyoman Sarimin",
        "Octarina Ratik Damayanti",
        "Oei Denny Kurniawan",
        "Oei Harry Lukmito",
        "Oentoro Surya",
        "Oerip Wirontono",
        "Oesman Sapta",
        "Oetie Hermawan",
        "Oey Aling Hermawan",
        "Okkie Adhika Tirta Monterie",
        "Omar Putihrai",
        "Ong Ju Chi",
        "Ong Mei Sian",
        "Ong Thiam Hok",
        "Ong Tiong Yun",
        "Ong Wen Nio",
        "Ongko Multicorpora",
        "Ongkowijoyo Onggowarsito",
        "Osbert Kosasih",
        "Oscar Gonzalo Guedez Machado",
        "Para Group",
        "Parveen Gandhi",
        "Pat Stratton",
        "Patrick Morris Alexander",
        "Patrick Walujo",
        "Paul Banuara Silalahi",
        "Paulis Amin Djohan",
        "Paulus Johanes",
        "Paulus Thio",
        "Payal Vijay Goklani",
        "Pe Sioe Kim",
        "Pedro Limardo",
        "Pek Teng Beng",
        "Permadi",
        "Pernardi Djojosudirdjo",
        "Perseroan Terbatas",
        "Peter Anthony Wallace",
        "Peter Bowden",
        "Peter Markart",
        "Peter Vinzenz Merkle",
        "Petrus Budiman Gho",
        "Petrus Budiyanto",
        "Phang Chin Liat",
        "Philip Strachan Attwood",
        "Philip Tjandra",
        "Piet Wijaya",
        "Pieter Tanuri",
        "Pinardi",
        "Piong Denisse Lucia",
        "Pipin Arifin Linggawidjaja",
        "Pirngady Adhi Wicaksono Himawan",
        "Piter Korompis",
        "Pitra Wiria",
        "Poniman",
        "Poppy Hadiman",
        "Poppy Tumengkol",
        "Pra Ciputra",
        "Pradeep Dudaney",
        "Soniya Dudaney",
        "Pradono Joko Trajutrisno Himawan",
        "Prakash Mohanlal Panjabi",
        "Vidhya Prakash Panjabi",
        "Prakoso Eko Setyawan Himawan",
        "Pramudji Suginawan",
        "Praptono Budhi Haksomo Himawan",
        "Prasodjo Winarko",
        "Prayitno Cipto Anggoro Himawan",
        "Prayugi Sukardjo",
        "Prem Ramchand Harjani",
        "Pri Wono",
        "Prijono Winarko",
        "Primanaga Hartanto Kalim",
        "Priyatno Sulisto",
        "Proboraras Mudoyo",
        "Pudjiastuti Binti Soemarno",
        "Pudjiono Iwansantoso",
        "Pujiastuti Elizabeth Sindoro",
        "Purnardi Djojosudirdjo",
        "Purwadi Hendropurnomo",
        "Purwoso Warsito Utomo Himawan",
        "Rachana Bhansali",
        "Rachmat Basuki Alimwidjaja",
        "Rachmat Gobel",
        "Rachmat Gunawan",
        "Rachmat Mulyana Hamami",
        "Rachmat Santoso Alimwidjaja",
        "Rachmat Susantyo",
        "Rachmat Sutiono",
        "Rachmiwaty",
        "Radisha Didi Utama",
        "Radius Christanto",
        "Rafael Buhay Concepcion Jr.",
        "Rahardjo Moecharar",
        "Rahendrawan Djoko",
        "Rahmad Pribadi",
        "Rahmawaty",
        "Raj Kumar",
        "Raja Sapta Ervian",
        "Raju Karamchandani",
        "Sara Raju Karamchandani",
        "Ramajati Tamin",
        "Randolph Adi Zaini",
        "Randy Hirawan",
        "Rashid Irawan Mangunkusumo",
        "Rasyid, Arwin",
        "Rat Anggraini Susantio",
        "Ratna Anggraini Susantio",
        "Ratna Christina",
        "Ratnasari Tamin",
        "Ratnawati Budiman",
        "Ratnawati Jenny Haryadi",
        "Ratnawati Sasongko",
        "Ratnawati Wihardjo",
        "Ratnesh Bedi",
        "Ravi Shyam Sadarangani",
        "Sonal Ravi Sadarangani",
        "Ravi T. Vasandani",
        "Ravi Tulsidas Vasandani",
        "Rayanusin Widjaja",
        "Raymond A. Klesc",
        "Raymond Patra",
        "Raymond Pribadi",
        "Raymond S. B.",
        "Raymond, Louis Couhault",
        "Razief Nur Usman",
        "Razif Susanto",
        "Reimer Aloan Simorangkir",
        "Rendra Tjajadi",
        "Retno Cahyaningtyas",
        "Reza Maulana",
        "Reza Pribadi",
        "Reza Sazly H Siregar",
        "Rhita Manik",
        "Ria Indriana Pasaman",
        "Ria Yulianty Tj he",
        "Rianto Lesmana",
        "Richard Anthony Schumacher",
        "Richard Cornwallis",
        "Richard Dian Santoso",
        "Richard Hamilton McCandless",
        "Richard L. McAdoo",
        "Richard Mohanlal Harjani",
        "Richard Sugianto",
        "Veronica Susianty Rachim",
        "Richard Tjandra",
        "Ricky Frederik",
        "Ricky Tandiono",
        "Ricky Tandriono",
        "Ridwan Irawan",
        "Rilantini Harjani Muljawan",
        "Rina Ciputra Sastrawinata",
        "Rinda Syafrinda",
        "Rini Mariani Soewandi",
        "Rini Susilo Putri",
        "Risty Istiana",
        "Rita Handoso",
        "Rita Indriawati",
        "Riza Mutyara",
        "Rizal Risjad",
        "Robby Rhemrev",
        "Robert Kevin Ellis",
        "Robert Priantono Bonosusatya",
        "Robert Sean King",
        "Roberto Hanna Jose",
        "Roberto Tampubolon",
        "Robin Liem",
        "Robin Makmur",
        "Roger Morrison",
        "Roger Pinder",
        "Roij Bramasiswadi Pura Widjaja",
        "Romo Nittyyudo Wacho",
        "Ronald E.P. Mullers",
        "Ronald Edward Philip Mullers",
        "Ronald Liem",
        "Ronald Mullers",
        "Ronald Rusco",
        "Ronald Wijaya",
        "Ronaldi Machmud",
        "Roni Faisal Siregar",
        "Roni Pramaditia",
        "Ronny Hadiana Angkasa",
        "Ronny Lukito",
        "Ronny Suryana",
        "Ronny Susanto",
        "Rony Moelyadi",
        "Rony Narpatisuta Medanlaga",
        "Roos Diana",
        "Roosmiati Handojo",
        "Rori Indra",
        "Rosan Perkasa Roeslani",
        "Rosana",
        "Roselyne Yosawiria",
        "Rosemelati S. Adikusumah",
        "Rosianawati Adikara",
        "Rosida Chung",
        "Rosmeiny Djaja Burhan",
        "Roswita Trismitro",
        "Roy E. Tirtadji",
        "Roy Gosjen",
        "Roy Kevin Kurniawan",
        "Roy Muljadi Soetikno",
        "Rubyanto F. Komala",
        "Rudi Darmawan",
        "Rudi Soraya",
        "Rudi Wirawan Rusli",
        "Rudy Cahyadi Sukandadinata",
        "Rudy Ghozali",
        "Rudy Hari",
        "Rudy Harjanto Widjaja",
        "Rudy Muljadi Atmawidjaja",
        "Rudy Nanggulangi",
        "Rudy Rayawang",
        "Rudy Soetikno",
        "Rudy Suhendra",
        "Rudy Susanto",
        "Suzie Ramli",
        "Rudy Unjoto",
        "Rudy Y.",
        "Rudyanto Gunawan",
        "Rudyanto Suliawan",
        "Rudyono",
        "Rulyani Basyir",
        "Runi Adianti",
        "Rusdi Kirana",
        "Rusdi Sunarjo",
        "Rusdy Budisusetyo",
        "Rusiana Susanto",
        "Rusjati Tamin",
        "Russel Bruce McDonald",
        "Russell McDonald",
        "Rustiyan Oen",
        "Ryan Pascal Masagung",
        "Ryandi Irawan",
        "Ryu Kawano",
        "Saad Shaarawi",
        "Sacheen Harris Lasmana",
        "Sadikun Wiratno",
        "Safersa Yusana Sertana",
        "Said Agil Assagaff",
        "Saiko Doi",
        "Salik Soetemo",
        "Salim Podiono",
        "Salim Santoso",
        "Sally Texania Marita Joesoef",
        "Sallyawati Rahardja",
        "Samin Tan",
        "Sammy Hamzah",
        "Samuel Setiawan",
        "Sanadi Boenyamin",
        "Sanderawati Joesoef",
        "Sandi Gunawan Ho",
        "Sandra Setijono",
        "Sandrawati Setiadi",
        "Sandria Kirana Budiendra",
        "Sangeeta Ramchand",
        "Sanjay Bhansali",
        "Sanjaya Raharja",
        "Loren",
        "Santoso Widjojo",
        "Santy Jennice Lioe",
        "Sanyo Leebrianto Suhaimi",
        "Saparuddin",
        "Sapri",
        "Saraswati Tedjakusuma",
        "Sardjono",
        "Sari Wulaningsih",
        "Satyadharma Ruslim",
        "Sefrie Roring",
        "Sembodo Broto Winarso",
        "Semiwati Lawanto",
        "Sengman Tjahja",
        "Septiana Iskandar",
        "Septo Adjie Sudiro",
        "Setia Budhi",
        "Setiabudi Djaelani",
        "Setiady Koeswojo",
        "Setiawan Achmad",
        "Setiawan Lukman",
        "Setiono Tandriono",
        "Sgfried Rinaldy",
        "Shalimar Sulisto",
        "Shaline Mary Shabna Soulsby",
        "Shariq Mukhtar",
        "Sherlly Hartono",
        "Sherman Rana Krishna",
        "Shih Chih-Hung",
        "Shinta Deviyanti",
        "Shinta Moetiara",
        "Shinta Sanjaya Ismael",
        "Shuzy Lipina",
        "Siak Tjai Oi",
        "Siauw Rachel Anatola",
        "Siauw Welly Susanto",
        "Siegfried Erwin Bengner",
        "Sierah Landajani Soetemo",
        "Sigit Iswandi",
        "Silkar National Limited",
        "Siman Darmamulia",
        "Simon C. Horn",
        "Simon Lim",
        "Simon Subrata",
        "Simon Susilo",
        "Simson Panjaitan",
        "Sinarto Dharmawan",
        "Sinatra Arto Hardy",
        "Sindhu Wibhisono Ongkosoewito",
        "Singgih Amara Widjanarko",
        "Singgih Kartono Halim Lie",
        "Siok Lim Tjoa",
        "Sistha Alicia Tjokrosaputro",
        "Siti Farihah",
        "Siti Hartati Tjakra Murdaya",
        "Sity Leo Samudera",
        "Siusan Hermawan",
        "Slamet Wibowo",
        "So Lai Fun",
        "Soebagjo Jatim Djarot",
        "Soebali Sudjie",
        "Soegianto Nagaria",
        "Soegiarto Djitowibowo",
        "Soegwanto",
        "Soekrisman Legiman",
        "Soemadipradja Taher",
        "Soenarjanto Indratono",
        "Soenarni Sampoerno",
        "Soenarta Natapradja",
        "Soendari Widjaja",
        "Soeparmadi",
        "Soeparman Hardjodikromo",
        "Soeroto Hadimuljono",
        "Soeryo Bawono",
        "Soesanto Effendi",
        "Soesilowati",
        "Soetikno Soedarjo",
        "Putri Rahayu Soedarjo",
        "Soetikno Tanoko",
        "Soetjahjono Winarko",
        "Soetjipto Nagaria",
        "Soewandi Gunawan",
        "Soeyanto",
        "Sofian Widagdo",
        "Sohet Chairil",
        "Soleh Mamun",
        "Solidi Korompis",
        "Solidi Silvester Korompis",
        "Solihin",
        "Solihin Asiah",
        "Solihin Yusuf Kalla",
        "Somboon Yuprapan",
        "Song Liang Hua",
        "Song Wen Po",
        "Jimmy Song",
        "Michael Song",
        "Song Wen Shyang",
        "Sonny Agustino Laksito",
        "Sony Rudikan",
        "Sonya Riupassa",
        "Sorgato Widjaja",
        "Sri Iriani Goenawan",
        "Sri Krishna Wishnu Wardhana",
        "Sri Mulyono Herlambang",
        "Sri Murwati Habir",
        "Sri Rahayu Setyawati",
        "Sri Setyaningsih Elisabeth",
        "Sri Soelijah",
        "Stan Maringka",
        "Stefanus Arief Chrisnamurti",
        "Stephan Putra Kurniawan",
        "Stephen Charles Dodgson",
        "Stephen Patra",
        "Steven Hirawan",
        "Steven Scott Barki",
        "Steven Sugianto",
        "Steven Tirtawidjaja",
        "Stewart Donald Hall",
        "Stewart James Robinson",
        "Stockcorp Limited",
        "Su Kam To",
        "Suarmin Tioniwar",
        "Dewi Salim",
        "Subagio Wirjoatmodjo",
        "Subardi",
        "Subari Setiono",
        "Subianto Arpan Sumodikoro",
        "Subianto Tjandra",
        "Subuh Hari Cahyanto",
        "Sudiarso Prasetio",
        "Sudijanto Atmodjo",
        "Sudiro Andi Wiguno",
        "Sudjono Barak Rimba",
        "Sudjono Karim",
        "Sufan Abner",
        "Sugianto Adiwinata",
        "Sugiharto",
        "Sugiharto Ta",
        "Sugiman",
        "Sugiono",
        "Sugiono Djauhari",
        "Sugiono Wiyono Sugialam",
        "Lanny Herawati Wibowo Ng",
        "Sugito Walujo",
        "Sugun Susilo",
        "Suhadi Zaini",
        "Suhangkat Lakmudin",
        "Suhardi",
        "Suhardi Budiman",
        "Suhardiman",
        "Suhardy",
        "Suhari Setiono",
        "Suharman Subianto",
        "Suhendra Gunadi",
        "Suherman Tjandradjaja",
        "Suhiantoro Supardjono",
        "Sujanty Jamin",
        "Sujarni",
        "Sujono Hadikusumo",
        "Sukendar Unjoto",
        "Sukmawati Widjata",
        "Sulaiman Hakim",
        "Sulaiman Leban Koswara",
        "Sulieniati Chandra Tjoe",
        "Sulistiani Sampoerna",
        "Sulung Poniman",
        "Sumadi",
        "Sumardi Kartasasmita alias Kong Phing Li",
        "Sumarto Wonowidjojo",
        "Sumet Jiaravanon",
        "Sumiati Liauw",
        "Sumiaty",
        "Sun Moon Suhaimi",
        "Sun Khai-Nien",
        "Sunan Susilo",
        "Sunardi",
        "Sunarjo Sampoerna",
        "Sunata Tjiterosampurno",
        "Sung Pui Man",
        "Sunil Motilal Mirpuri",
        "Sunny Suhaimi",
        "Supardi",
        "Supartono Suparto",
        "Suresh Narsinhdas Shah",
        "Suria Kurniawan Lukiman",
        "Suriawati Tan",
        "Suripto",
        "Surjadinata Sumantri",
        "Surjantoro Siswanto",
        "Surjany Kurniawan Eckert",
        "Surjono Tanoto",
        "Surono",
        "Surya Laksana Ongkoredjo",
        "Suryadiharja Freddi H.",
        "Suryana Tochmi",
        "Suryana Nurzaman Zein",
        "Suryanto",
        "Suryawati L. Riady",
        "Susan Lo",
        "Susana Sutanto",
        "Susanna Kusnowo",
        "Susanna Nagaria",
        "Susanti Pheng",
        "Susanti Sunardi",
        "Susanto",
        "Susanto Suwarto",
        "Susanto Tandra",
        "Susanto Tjandra",
        "Susanto Winarto",
        "Susi Salamah",
        "Susilawati",
        "Susilo Soputro",
        "Susilo Wonowidjojo",
        "Susilowati",
        "Susin Valentinus",
        "Suswanti Gunawan",
        "Susy Angkawijaya",
        "Susy Gunawan",
        "Sutanto Djuhar",
        "Sutanto Leon Patrick",
        "Sutarsa Tanu",
        "Sutiadi Widjaja",
        "Sutiadi Widjaya",
        "Sutiana Juhanda",
        "Sutikno",
        "Sutono Nitisastro",
        "Suwandi Widjaja",
        "Suwantara Gotama Lim",
        "Suwito Brodjonegoro",
        "Suwito Muliadi",
        "Suyono Purnomo",
        "Suzie Surjana",
        "Tony Surjana",
        "Syahbandi",
        "Syahrul",
        "Syaiful Zen",
        "Syamsul Hoiri",
        "Syarief Tando",
        "Syarif Bastaman",
        "Sylvia Efi Widyantari Sumarlin",
        "Sylvia Mardiana Sarwani",
        "Sylvia Muljadi",
        "Sylvia Novieta",
        "Symon Brewis Weston",
        "Tahi Parulian Saragi",
        "Tan Ali Susanto",
        "Tan Hong Kiem",
        "Tan Loo Mei",
        "Tan Lucas Adnan Soen Hwat",
        "Tan Lunardi",
        "Tan Olinda Dewi",
        "Tan Timothy Tandon",
        "Tan Tjoe Liang",
        "Tanaka Kazuya",
        "Tanaka Kiyomi",
        "Tandean Rustandy",
        "Susan Sujanto",
        "Tang Eng Hoo",
        "Tansri Soen Zen",
        "Targian Tan",
        "Tatang Hermawan",
        "Taufan",
        "Taufik Surya Dharma",
        "Tay Robinto",
        "Teddy Fadil",
        "Teddy Jeffrey Katuari",
        "Teddy Sugianto",
        "Teddy Sutandinata",
        "Teddy Tjahjono",
        "Teddy Yoshawirja",
        "Tedja Widjaja",
        "Tedy Tanumihardja",
        "Teguh Arianto Budiman",
        "Teguh Boentoro",
        "Teguh Ganda Wijaya",
        "Teguh Suginawan",
        "Teng Goat Nio",
        "Tengku Muhammad Ali Mahara",
        "Teresa Suteja",
        "Terunodjojo Nusa",
        "Texmaco Group",
        "The Hie Ting",
        "The Kwen Ie",
        "The Liliana",
        "The Practice",
        "The Wen Jun",
        "Theodorus Marto Sutiono",
        "Theresia Lidwina",
        "Theresia Suciah",
        "Theresia Widyawati Setiono",
        "Theresia Yustina Sumarlin",
        "Thio Julia Timotius",
        "Thomas Derek Wilkes Burland",
        "Thomas Lundi Halim",
        "Thomas M. Tampi",
        "Thomas Soulsby",
        "Thomas Tampi",
        "Thomson",
        "Tiara Dharani Josodirdjo",
        "Tien Thinh Pham",
        "Tigran Timotius Adhiwiyogo",
        "Timmie Melvin",
        "Timothius Felix Intan",
        "Timothy James Supple",
        "Timothy Siddik",
        "Timothy Watts",
        "Tina Meimona Shazell",
        "Tina Suteja",
        "Tio Imelda",
        "Tirta Juwana Darmadji",
        "Tirtadjaja Hambali",
        "Tirto Angesti",
        "Tirto Angesty",
        "Tito Sulistio",
        "Titus Wahjoe Dewanto",
        "Tjahjadi Hari Surjono",
        "Tjahjadi Rahardja",
        "Tjahjadi Tresna",
        "Tin Tin Tresna",
        "Senjaya Tresna",
        "Tjahjono Alim",
        "Tjahyono Imawan",
        "Tjan Kok Pin",
        "Tjandra Sari",
        "Tjandra Teresna Widjaja",
        "Tjhang Hwee Tjoe",
        "Tjia Tjhun Hwa",
        "Tjia Tjoen Hiong",
        "Tjia Tjoen Hok",
        "Tjia Wiwin Anggono",
        "Tjiam Ming Ping",
        "Tjie Jien Wang",
        "Tjindrasa Ng",
        "Tjioe Hauw Tze",
        "Tjioe Gunawan Adianto",
        "Tjipto Surjanto",
        "Tjiu Thomas Effendy",
        "Tjoa Siok Lim",
        "Tjoe Hendry",
        "Tjoe Meuw Sen",
        "Tjoi Wilson",
        "Tjokrorianto",
        "Tjondro Indria Liemonta",
        "Tjong Euw Khiong",
        "Tjong Jok Ha",
        "Tjong Miranti",
        "Tjong Tje Liong",
        "Tjong Tje Tjin",
        "Toddy Mizaabianto Sugoto",
        "Tom Soulsby",
        "Tommy Jacobus Silfanus",
        "Tommy Laurens",
        "Tommy Nugraha",
        "Tommy Tanady",
        "Tomy Wikutomojati",
        "Tonny Raidy Djamhir",
        "Tonny Wantah",
        "Tony Djayalaksana",
        "Tony Supargo",
        "Tossin Suharya",
        "Stephen Ignatius Suharya",
        "Daniel Suharya",
        "Toto Soegiarto",
        "Totok Susilo",
        "Totty Moekardiono",
        "Trent Karoll",
        "Triana Soenryo",
        "Trianawati",
        "Tricia Barki",
        "Trini Koeswanti Sri Soepardianti",
        "Triyono Juliarso Dawis",
        "Trisnawati Budiman",
        "Trisning Setiadi",
        "Triyatno Atmodiharjo",
        "Troy Surya Subandi",
        "Tsang Kam Heung",
        "Tseng Hsueh Sung",
        "Tseng, Hsueh Sung",
        "Tung Bibiana",
        "Tunggono",
        "Turcahyo Wahyudi",
        "Turniady Widjaja",
        "Yessica Beatrice Widjaja",
        "Tuty Sumargo",
        "Tyrone Kaskam Awan",
        "Tyty Chandra",
        "Ulian Napsiah",
        "Umar Suwandi",
        "Ungkoro Darmosusilo",
        "Untoro Angkawijaya",
        "Upekkha Theresia Murdaya",
        "Ustadai Tedja",
        "Gan Ying May",
        "Felix Tedja",
        "Edwin Tedja",
        "Ustadi Tedja",
        "Utama Gondokusumo",
        "Utama Halim",
        "Utama Jusuf",
        "Megawati Hartono",
        "Eddy Jusuf",
        "Angela Jusuf",
        "Utaryo Suwanto",
        "Utomo Djohan",
        "Uwat",
        "Varisa Susilo",
        "Vemmy Febriyanti",
        "Vera Marlinata Widjaya",
        "Vernon Charles Lee",
        "Veronica Lukito",
        "Veronica Colondam",
        "Veronica Devi Intan",
        "Veronica Renata",
        "Veronica Tjendro Susanto",
        "Veronika Slamet",
        "Victor Fungkong",
        "Victor Luhur",
        "Victor Sebastian Vaz",
        "Vijay Naraindas Gangtani",
        "Vincent Kus Chu",
        "Vinod Kumar Agarwal",
        "Viona Gunawan",
        "Virendra Prakash Sharma",
        "Vivi Hottama",
        "Vivian Kent Janawati",
        "Vivien Goh",
        "Vonny Harsono",
        "Vonny Juwono",
        "Wachid Hendriadi",
        "Lizza Christina Budihardjo",
        "Wadyono Suliantoro",
        "Setijanti Suliantoro",
        "Wahjudin Judiana Ardiwinata",
        "Wahyu Subayani",
        "Wahyu Tri Laksono",
        "Wahyudi Lukmantara",
        "wan peng lim",
        "Wei Zhigang",
        "Welly Thomas",
        "Wen Shyang Song",
        "Wewey Tjahjadi",
        "Wewey Tjahjadi Wanadihardja",
        "Whitlam Luhur",
        "Wibawa Darmawan",
        "Wibowo Brotorahardjo",
        "Wibowo Kartopranoto",
        "Wibowo Suseno Wirjawan",
        "Wicahyo Ratomo",
        "Wida Martha Sari Newton",
        "Widhayati Hendropurnomo",
        "Widhi Sesanti",
        "Widiyanti Putri",
        "Widjaja Trisna",
        "Widjaya Sendra",
        "Widjojo Budiarto",
        "Widjojo Parawirohardjo",
        "Widjojo Soejono",
        "Widyakumala Sulistyo",
        "Widyawati Budiman",
        "Wientoro Prasetyo",
        "Wijayanto Ang",
        "Wijono Widjojo",
        "Wilfred Schultz",
        "Wilhelmina Bia Mugirato",
        "William A. Sullivan",
        "William James Park",
        "Yuliati Karnadi",
        "William Lietanawaty",
        "William Shane Tan",
        "William Sutjiatma",
        "William T. Jugiarto",
        "Willie Tandanu",
        "Willy Lukito",
        "Willy Sugianto",
        "Wina Widjaja",
        "Winardi Darmansa Lim",
        "Winardi Setiaputra",
        "Winardi Thamrin",
        "Winarno Tjajadi",
        "Lili Liauw",
        "Sujanto Tjajadi Tjio",
        "Winarto Halim",
        "Winata Wiryaputra",
        "Winny Martina Christine",
        "Wira Satria Dewo Anggoro Kasih",
        "Wirawan Chondro",
        "Wisasongko Puspoyo",
        "Witijasmoro Sih Handajanto",
        "Witjaksono Abadiman Sidharta",
        "Wito Chandra",
        "Witono Dani",
        "Wiwiek Hidajati",
        "Wiwin Untari Andoko",
        "Wiyang",
        "Wong Alfian Widjaya",
        "Wong Chuk Chen",
        "Wong Steffania",
        "Wong Tommy Wibowo",
        "Wong Tranadi",
        "Siong Yuit Benjamin",
        "Xu Jun",
        "Xu Peng",
        "Yakin Lijaya",
        "Yamin Widjaja",
        "Yanto Kasiman",
        "Yanuar Tenacious",
        "Yap Eng Siu",
        "Yap Johanes",
        "Yau Hang Yip",
        "Yau Yung",
        "Yaya Winarno Junardy",
        "Yayasan Chandra Bunda Dewi",
        "Yeni Rohaeni",
        "Yogie Sandi Yudhianto",
        "Yohan Sutandar",
        "Yohanes Eka Putranto",
        "Yohannes Alexander Wintery Oei",
        "Yohannes Riyadi",
        "Yoko Kawano",
        "Yolanda Wijaya",
        "Yong Wiyono Buyung Yasin",
        "Yonna Septarina Kusdianto",
        "Yos Hendri",
        "Yoseph Suherman",
        "Yosodewi Limurti",
        "Yosyan Madolen",
        "Yoyok Soebagio",
        "Yudi Astono",
        "Yugisako Tita",
        "Yuke Elia Susiloputro",
        "Yulia Sinta Dewi",
        "Yuliana Sudradjat",
        "Yully",
        "Yunet Limanto",
        "Yunie Wono",
        "Yunita Kalim",
        "Yunita Sastrasanjaya",
        "Yusak Teguh Nugroho",
        "Yustiningsih Suharsono",
        "Yustinus Wisnoe Bayuaji",
        "Yusuf Adrian Chandra",
        "Yusuf Valent",
        "Yusy Widjaja Oey",
        "Yvonne Shirley Fogarty",
        "Zaini Abidin Noor",
        "Zuriah",
    ]


class Utility:
    nisnObject = {}
    tahunMasukToTingkat = {2020: "XII", 2021: "XI", 2022: "X"}

    def readJSON(path):
        return json.load(open(path))

    def writeJSON(path, data):
        with open(path, "w") as outfile:
            outfile.write(json.dumps(data, indent=4))

    def randomNISN(start, end):
        enrollmentNumber = str(random.randint(start, end))

        newEnrollmentNumber = True
        for nisKey in Utility.nisnObject.items():
            if enrollmentNumber == nisKey[0]:
                newEnrollmentNumber = False

        if newEnrollmentNumber:
            Utility.nisnObject[enrollmentNumber] = 1

        elif not newEnrollmentNumber:
            Utility.nisnObject[enrollmentNumber] += 1

        idkNumber = str(719)
        countNumber = str(Utility.nisnObject[enrollmentNumber]).zfill(3)

        nis = int(enrollmentNumber + idkNumber + countNumber)

        return nis

    def randomTempatLahir():
        return (random.choice(Utility.tempatLahirArray))["_id"]

    def randomBirthDate(start, end):
        timeFormat = "%Y/%m/%d"

        stime = time.mktime(time.strptime(start, timeFormat))
        etime = time.mktime(time.strptime(end, timeFormat))

        ptime = stime + random.random() * (etime - stime)

        return time.strftime(timeFormat, time.localtime(ptime))

    def randomJenisKelamin():
        return (random.choice(Utility.jenisKelaminArray))["_id"]

    def randomTahunMasuk():
        return (random.choice(Utility.tahunMasukArray))["_id"]

    def randomTingkat():
        return (random.choice(Utility.tingkatArray))["_id"]

    def randomJurusan():
        return (random.choice(Utility.jurusanArray))["_id"]

    def randomRombel():
        return (random.choice(Utility.rombelArray))["_id"]

    def dateToUnix(date):
        return str(int(datetime.strptime(date, "%Y/%m/%d").timestamp()) * 1000)

    def currentDate():
        return str(int(datetime.today().timestamp()) * 1000)

    tempatLahirArray = readJSON("scripts/json/tempat_lahir.json")
    jenisKelaminArray = readJSON("scripts/json/jenis_kelamin.json")
    tahunMasukArray = readJSON("scripts/json/tahun_masuk.json")
    tingkatArray = readJSON("scripts/json/tingkat.json")
    jurusanArray = readJSON("scripts/json/jurusan.json")
    rombelArray = readJSON("scripts/json/rombel.json")


class Main:
    def main():
        Main.tempatLahir()
        Main.jenisKelamin()
        Main.tahunMasuk()
        Main.tingkat()
        Main.jurusan()
        Main.rombel()
        Main.siswa()

    def tempatLahir():
        tempatLahirArray = []
        for tempatLahirIndex, tempatLahir in enumerate(Dependency.tempatLahirArray):
            tempatLahirObject = {
                "_id": tempatLahirIndex + 1,
                "tempat_lahir": tempatLahir,
            }

            tempatLahirArray.append(tempatLahirObject)

        Utility.writeJSON("scripts/json/tempat_lahir.json", tempatLahirArray)

    def jenisKelamin():
        jenisKelaminArray = []
        for jenisKelaminIndex, jenisKelamin in enumerate(Dependency.jenisKelaminArray):
            jenisKelaminObject = {
                "_id": jenisKelaminIndex + 1,
                "jenis_kelamin": jenisKelamin,
            }

            jenisKelaminArray.append(jenisKelaminObject)

        Utility.writeJSON("scripts/json/jenis_kelamin.json", jenisKelaminArray)

    def tahunMasuk():
        tahunMasukArray = []
        for tahunMasukIndex, tahunMasuk in enumerate(Dependency.tahunMasukArray):
            tahunMasukObject = {
                "_id": tahunMasukIndex + 1,
                "tahun_masuk": tahunMasuk,
            }

            tahunMasukArray.append(tahunMasukObject)

        Utility.writeJSON("scripts/json/tahun_masuk.json", tahunMasukArray)

    def tingkat():
        tingkatArray = []
        for tingkatIndex, tingkat in enumerate(Dependency.tingkatArray):
            tingkatObject = {
                "_id": tingkatIndex + 1,
                "tingkat": tingkat,
            }

            tingkatArray.append(tingkatObject)

        Utility.writeJSON("scripts/json/tingkat.json", tingkatArray)

    def jurusan():
        jurusanArray = []
        for jurusanIndex, jurusan in enumerate(Dependency.jurusanArray):
            jurusanObject = {
                "_id": jurusanIndex + 1,
                "jurusan": jurusan,
            }

            jurusanArray.append(jurusanObject)

        Utility.writeJSON("scripts/json/jurusan.json", jurusanArray)

    def rombel():
        rombelArray = []
        rombelCount = 0
        for tingkat in Dependency.tingkatArray:
            for rombel in Dependency.rombelArray:
                rombelObject = {
                    "_id": rombelCount + 1,
                    "rombel": f"{tingkat} {rombel}",
                }

                rombelCount += 1

                rombelArray.append(rombelObject)

        Utility.writeJSON("scripts/json/rombel.json", rombelArray)

    def siswa():
        siswaArray = []
        siswaCount = 0
        for tahunMasuk in Utility.tahunMasukArray:
            tahunMasukValue = tahunMasuk["tahun_masuk"]
            tahunMasuk2Digit = int(str(tahunMasukValue)[-2:])
            birthDateStart = f"{2004 - 20 + tahunMasuk2Digit}/01/01"
            birthDateEnd = f"{2006 - 20 + tahunMasuk2Digit}/12/31"

            tingkatValue = Utility.tahunMasukToTingkat[tahunMasukValue]

            for tingkatObject in Utility.tingkatArray:
                if tingkatObject["tingkat"] in tingkatValue:
                    tingkat = tingkatObject

            for rombel in Dependency.rombelArray:
                namaUniqueArray = random.sample(
                    Dependency.nameArray, k=random.randint(34, 36)
                )

                for jurusanObject in Utility.jurusanArray:
                    if jurusanObject["jurusan"] in rombel:
                        jurusan = jurusanObject

                for rombelObject in Utility.rombelArray:
                    if rombelObject["rombel"] in f"{tingkat['tingkat']} {rombel}":
                        rombelValue = rombelObject

                for namaUnique in namaUniqueArray:
                    siswaObject = {
                        "_id": siswaCount + 1,
                        "nisn": Utility.randomNISN(tahunMasuk2Digit, tahunMasuk2Digit),
                        "nama_lengkap": namaUnique,
                        "id_tempat_lahir": Utility.randomTempatLahir(),
                        "tanggal_lahir": {
                            "$date": {
                                "$numberLong": Utility.dateToUnix(
                                    Utility.randomBirthDate(
                                        birthDateStart, birthDateEnd
                                    )
                                )
                            }
                        },
                        "id_jenis_kelamin": Utility.randomJenisKelamin(),
                        "id_tahun_masuk": tahunMasuk["_id"],
                        "id_tingkat": tingkat["_id"],
                        "id_jurusan": jurusan["_id"],
                        "id_rombel": rombelValue["_id"],
                        "dibuat": {"$date": {"$numberLong": Utility.currentDate()}},
                        "diubah": {"$date": {"$numberLong": Utility.currentDate()}},
                    }

                    siswaCount += 1

                    siswaArray.append(siswaObject)

        Utility.writeJSON("scripts/json/siswa.json", siswaArray)


Main.main()
